### ISSUE TITLE
検索結果のページのUI

### ISSUE THREAD

**Issue by chakku000** [IQ1-ITSP/OCW4IQ1#3]
検索結果のページのUIの作成

表示する内容は検索した対象となる授業一覧

- 基本的なUIはトップページ #2 に準拠(?)

**Comment by chakku000** [comment]
誰がやるんだ....

**Comment by chakku000** [comment]
僕がやりますね

**Comment by chakku000** [comment]
UIをトップページに合わせました

**Comment by chakku000** [comment]
https://github.com/IQ1-ITSP/OCW4IQ1/tree/issue/3
@hi-watana 
実装授業詳細ページを実装したので誰か動作を確認してくれればこのissueは閉じます

**Comment by khiranouchi** [comment]
確認しました。
