### ISSUE TITLE
Databaseの使用/構築方法の調査

### ISSUE THREAD

**Issue by chakku000** [IQ1-ITSP/OCW4IQ1#6]
データベースの使用方法の調査
使用するデータベースはMySQL
実際に使うものを構築するところまではやらなくてもよい
@Yuki-snp 

- [ ] どうやって構築するか
- [ ] どうやってアクセスするか
- [ ] (優先度低) できればdockerを使用できるか (手元とサーバー側で同じ環境を作りたい)

**Comment by Yuki-snp** [comment]
Django データベース操作 についてのまとめ
https://qiita.com/okoppe8/items/66a8747cf179a538355b

**Comment by Yokohama-Miyazawa** [comment]
PythonでMySQLを操作する方法：MySQLdb
http://uxmilk.jp/23509

**Comment by Yuki-snp** [comment]
MySQLをMacに導入して基礎を学ぶ
https://qiita.com/yamagenii/items/ba9c737fef11409447be

↑でサーバーを立ち上げたら

Python3でMySQLを操作する
http://kzhishu.hatenablog.jp/entry/2017/06/03/162911

サーバー上にはPyMySQLをhi-watana君に入れてもらいました

**Comment by chakku000** [comment]
ローカルで動作を確認
